version: '3.2'

services:
  gateway:
    image: functions/gateway:0.6.6-beta
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      dnsrr: 'true'
    deploy:
      placement:
        constraints:
          - 'node.role == manager'
          - 'node.platform.os == linux'
    ports:
      - 8080:8080
    networks:
      - functions

  ftrigger-kafka:
    image: ucalgary/ftrigger:master
    command: kafka-trigger
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - functions
      - streaming

  echoit:
    image: functions/alpine:health
    labels:
      function: "true"
    environment:
      fprocess: "cat"
      no_proxy: "gateway"
      https_proxy: $https_proxy
    deploy:
      placement:
        constraints:
          - 'node.platform.os == linux'
      labels:
        ftrigger.kafka: 'true'
        ftrigger.kafka.topic: 'echo'
    networks:
      - functions

  zookeeper:
    image: confluentinc/cp-zookeeper:${CONFLUENT_PLATFORM_VERSION}
    hostname: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - streaming

  kafka:
    image: confluentinc/cp-kafka:${CONFLUENT_PLATFORM_VERSION}
    hostname: kafka
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    networks:
      - streaming

  kafka-rest:
    image: confluentinc/cp-kafka-rest:${CONFLUENT_PLATFORM_VERSION}
    hostname: kafka-rest
    environment:
      - ACCESS_CONTROL_ALLOW_ORIGIN_DEFAULT="*"
      - KAFKA_REST_SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - KAFKA_REST_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_REST_HOST_NAME=kafka-rest
      - KAFKA_REST_LISTENERS=http://kafka-rest:8082
      - KAFKA_REST_BOOTSTRAP_SERVERS=PLAINTEXT://kafka:9092
    ports:
      - 8082:8082
    networks:
      - streaming

  schema-registry:
    image: confluentinc/cp-schema-registry:${CONFLUENT_PLATFORM_VERSION}
    hostname: schema-registry
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081
    networks:
      - streaming

  kafka-topics-ui:
    image: landoop/kafka-topics-ui:0.9.2
    environment:
      - KAFKA_REST_PROXY_URL=http://kafka-rest:8082
      - PROXY=true
    ports:
      - 8000:8000
    networks:
      - streaming
    
networks:
  functions:
  streaming: